import * as React from "react";
import styles from "../styles/Home.module.css";

import Head from "next/head";
import Header from "../components/Header/Header";
import { cartData } from "../interfaces/interfaces";

import HeroSection from "../components/HeroSection/HeroSection";
import ProductSection from "../components/ProductSection/ProductSection";

export default function Home() {
  const [cart, setCart] = React.useState<cartData[]>([]);
  const [showCart, setShowCart] = React.useState<boolean>(false);
  const [cartLength, setCartLength] = React.useState<number>(0);

  //add to cart
  const addToCart = (el: cartData) => {
    cart.push(el);
    setCartLength(cart.length);
    setShowCart(true);
  };

  const clearCart = () => {
    setCart([]);
    setCartLength(0);
    setShowCart(false);
  };

  const hideCart = () => {
    setShowCart(false);
  };

  const toggleShowCart = () => {
    setShowCart(!showCart);
  };

  return (
    <div>
      <Head>
        <title>Bejamas - Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        cart={cart}
        cartLength={cartLength}
        clearCart={clearCart}
        showCart={showCart}
        hideCart={hideCart}
        toggleShowCart={toggleShowCart}
      />
      <HeroSection addToCart={addToCart} />
      <div className={styles.productSection}>
        <ProductSection addToCart={addToCart} />
      </div>
    </div>
  );
}
